"""3D 백필 드라이버: GLB 변환 후 메타 승격 + 해시 + R2 병렬 업로드 (§22 Phase 2).
실행: python generators/backfill_drive.py  (gen_ipc3d.py → stl_to_glb.py 이후)"""
import hashlib
import json
import os
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor

sys.stdout.reconfigure(encoding="utf-8")
ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))


def sha(p):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for c in iter(lambda: f.read(1 << 20), b""):
            h.update(c)
    return h.hexdigest()


def upload(args):
    key, fpath = args
    for _ in range(3):
        r = subprocess.run(["npx", "wrangler", "r2", "object", "put", key,
                            "--file", fpath, "--remote"],
                           cwd=os.path.join(ROOT, "mcp"), capture_output=True,
                           text=True, encoding="utf-8", errors="replace", shell=True)
        if r.returncode == 0:
            return None
    return key


def main():
    idx = json.load(open(os.path.join(ROOT, "index.json"), encoding="utf-8"))
    jobs = []
    promoted = 0
    for p in idx["parts"]:
        d = os.path.join(ROOT, p["path"])
        fid = p["id"]
        glb = os.path.join(d, fid + ".glb")
        step = os.path.join(d, fid + ".step")
        mp = os.path.join(d, "meta.json")
        meta = json.load(open(mp, encoding="utf-8"))
        if meta.get("tier") != "verified-2d" or not os.path.exists(glb):
            continue
        meta["files"]["model_3d"] = fid + ".step"
        meta["files"]["preview"] = fid + ".glb"
        for f in ("step", "glb"):
            if f not in meta["formats"]:
                meta["formats"].append(f)
        meta.pop("tier", None)
        meta["description"] = meta["description"].replace(
            "Verified-2D part: upstream ships no 3D models.",
            "3D model generated parametrically from the IPC-7351 package name and "
            "the footprint's own pad geometry (PartReel).")
        meta.setdefault("import", {}).setdefault("modifications", []).append(
            "parametric 3D (STEP/GLB) generated by PartReel from IPC package name "
            "+ pad geometry")
        meta["asset_sha256"] = {fid + ".step": sha(step), fid + ".glb": sha(glb)}
        json.dump(meta, open(mp, "w", encoding="utf-8"), indent=2, ensure_ascii=False)
        rel = p["path"].replace("\\", "/")
        jobs += [(f"partreel-assets/{rel}/{fid}.step", step),
                 (f"partreel-assets/{rel}/{fid}.glb", glb)]
        promoted += 1
    print(f"promoted {promoted} parts, uploading {len(jobs)} files...")
    fails = []
    with ThreadPoolExecutor(10) as ex:
        for i, r in enumerate(ex.map(upload, jobs)):
            if r:
                fails.append(r)
            if (i + 1) % 200 == 0:
                print(f"uploaded {i + 1}/{len(jobs)}")
    print(f"upload done, fails {len(fails)}")
    if fails:
        json.dump(fails, open(os.path.join(ROOT, "docs", "r2-upload-fails.json"),
                              "w", encoding="utf-8"), indent=1)
        sys.exit(1)


if __name__ == "__main__":
    main()
