/* pins.h — generated by build_board.py from boards/demo_g431_devkit/board.json
 * rev 0.1 — DO NOT EDIT (source: board.json)
 */
#ifndef PARTREEL_PINS_H
#define PARTREEL_PINS_H

#define SCL_GPIO_Port GPIOA
#define SCL_Pin GPIO_PIN_15
#define SDA_GPIO_Port GPIOB
#define SDA_Pin GPIO_PIN_7
#define SWO_GPIO_Port GPIOB
#define SWO_Pin GPIO_PIN_3
#define USB_DM_GPIO_Port GPIOA
#define USB_DM_Pin GPIO_PIN_11
#define USB_DP_GPIO_Port GPIOA
#define USB_DP_Pin GPIO_PIN_12

#endif /* PARTREEL_PINS_H */
